// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yb.Dal.Base;

#nullable disable

namespace Yb.Dal.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Yb.Model.Cms.News", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Attach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckMemo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CheckStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreateUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Hit")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsHead")
                        .HasColumnType("int");

                    b.Property<int>("IsRec")
                        .HasColumnType("int");

                    b.Property<int>("IsTop")
                        .HasColumnType("int");

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Yb.Model.Sys.YbUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckMemo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CheckStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreateUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DataAuthority")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("UserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("YbUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
